name: implicit
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile=0.8.1
  - python=3.9
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - pytorch-scatter
  - opencv
  - tqdm
  - pip:
    - einops
    - wandb
    - lpips
    - laspy
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - gradio_imageslider
    - gradio
    - matplotlib

